### ISSUE TITLE
Denunciar URLs maliciosos

### ISSUE THREAD

**Issue by osouza-de** [mthbernardes/tadeboa#1]
Ao confirmar que o domínio é malicioso, enviar para os orgãos responsáveis (carece de fontes) e, se possível, enviar para a empresa "verdadeira".

**Comment by mthbernardes** [comment]
@d4nd complicado isso de reportar para os orgãos responsaveis, até onde eu sei, não existe isso.
E em relação de enviar para empresa verdadeira, muitas vezes eles não vão fazer nada, o que vai ser aberto issue é para que os usuarios reportem sites maliciosos, e ai se outra pessoa buscar por esse site, já vai ter os reports dos usuarios.
